-- Database: homefix_db

CREATE DATABASE IF NOT EXISTS homefix_db;
USE homefix_db;

-- 1. Users Table
CREATE TABLE IF NOT EXISTS Users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('Customer', 'Provider', 'Admin') DEFAULT 'Customer',
  phone VARCHAR(50),
  address VARCHAR(255),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 2. Services Table
CREATE TABLE IF NOT EXISTS Services (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  category VARCHAR(100) NOT NULL,
  basePrice DECIMAL(10, 2) NOT NULL,
  iconUrl VARCHAR(255),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 3. Providers Table
CREATE TABLE IF NOT EXISTS Providers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  experienceYears INT NOT NULL DEFAULT 0,
  bio TEXT,
  isVerified BOOLEAN DEFAULT FALSE,
  rating FLOAT DEFAULT 0.0,
  userId INT NOT NULL,
  serviceId INT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY (serviceId) REFERENCES Services(id) ON DELETE SET NULL
);

-- 4. Bookings Table
CREATE TABLE IF NOT EXISTS Bookings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  status ENUM('Pending', 'Accepted', 'InProgress', 'Completed', 'Cancelled') DEFAULT 'Pending',
  scheduledDate DATETIME NOT NULL,
  totalAmount DECIMAL(10, 2) NOT NULL,
  notes TEXT,
  address VARCHAR(255) NOT NULL,
  customerId INT NOT NULL,
  providerId INT NOT NULL,
  serviceId INT NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (customerId) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY (providerId) REFERENCES Providers(id) ON DELETE CASCADE,
  FOREIGN KEY (serviceId) REFERENCES Services(id) ON DELETE CASCADE
);

-- 5. Reviews Table
CREATE TABLE IF NOT EXISTS Reviews (
  id INT AUTO_INCREMENT PRIMARY KEY,
  rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  customerId INT NOT NULL,
  providerId INT NOT NULL,
  bookingId INT NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (customerId) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY (providerId) REFERENCES Providers(id) ON DELETE CASCADE,
  FOREIGN KEY (bookingId) REFERENCES Bookings(id) ON DELETE CASCADE
);

-- 6. Payments Table
CREATE TABLE IF NOT EXISTS Payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  amount DECIMAL(10, 2) NOT NULL,
  status ENUM('Pending', 'Completed', 'Failed', 'Refunded') DEFAULT 'Pending',
  paymentMethod VARCHAR(100),
  transactionId VARCHAR(255),
  bookingId INT NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (bookingId) REFERENCES Bookings(id) ON DELETE CASCADE
);
